apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-flight-connector
  labels:
    app: cf-flight-connector

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cf-flight-connector

  template:
    metadata:
      labels:
        app: cf-flight-connector

    spec:
      containers:
      - name: cf-flight-connector
        image: ghcr.io/marek-zuwala/connectors-forge:1.0.1
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 9443
          name: grpc
          protocol: TCP

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        volumeMounts:
        - name: config-volume
          mountPath: /config/mappings
          readOnly: true

      volumes:
      - name: config-volume
        configMap:
          name: connectors-config