apiVersion: v1
kind: Service
metadata:
  name: cf-flight-connector-service
<<<<<<< HEAD
=======
  namespace: connectorsforge
>>>>>>> 4a8a02f (codeless openshift)
  labels:
    app: cf-flight-connector
spec:
  type: ClusterIP
  selector:
    app: cf-flight-connector
  ports:
  - name: grpc
    port: 9443
    targetPort: 9443
    protocol: TCP
    appProtocol: grpc

# Made with Bob
