{
  "#hostname": "https://api.spacexdata.com",
  "COMPANY": {
    "#path": [
      "/v4/company"
    ],
    "id": "VarChar(50),#key",
    "name": "VarChar(100)",
    "founder": "VarChar(100)",
    "founded": "Integer",
    "employees": "Integer",
    "vehicles": "Integer",
    "launch_sites": "Integer",
    "test_sites": "Integer",
    "ceo": "VarChar(100)",
    "cto": "VarChar(100)",
    "coo": "VarChar(100)",
    "cto_propulsion": "VarChar(100)",
    "valuation": "BigInt",
    "summary": "LongVarChar(2000)",
    "headquarters": "JSON",
    "links": "JSON"
  },
  "ROCKETS": {
    "#path": [
      "/v4/rockets"
    ],
    "id": "VarChar(50),#key",
    "name": "VarChar(100)",
    "type": "VarChar(50)",
    "active": "Boolean",
    "stages": "Integer",
    "boosters": "Integer",
    "cost_per_launch": "BigInt",
    "success_rate_pct": "Integer",
    "first_flight": "Date",
    "country": "VarChar(100)",
    "company": "VarChar(100)",
    "wikipedia": "VarChar(500)",
    "description": "LongVarChar(2000)",
    "height": "JSON",
    "diameter": "JSON",
    "mass": "JSON",
    "first_stage": "JSON",
    "second_stage": "JSON",
    "engines": "JSON",
    "landing_legs": "JSON",
    "payload_weights": "JSON",
    "flickr_images": "JSON"
  },
  "CAPSULES": {
    "#path": [
      "/v4/capsules"
    ],
    "id": "VarChar(50),#key",
    "serial": "VarChar(50)",
    "status": "VarChar(50)",
    "type": "VarChar(50)",
    "reuse_count": "Integer",
    "water_landings": "Integer",
    "land_landings": "Integer",
    "last_update": "LongVarChar(1000)",
    "launches": "JSON"
  },
  "CREW": {
    "#path": [
      "/v4/crew"
    ],
    "id": "VarChar(50),#key",
    "name": "VarChar(200)",
    "agency": "VarChar(100)",
    "image": "VarChar(500)",
    "wikipedia": "VarChar(500)",
    "status": "VarChar(50)",
    "launches": "JSON"
  },
  "CORES": {
    "#path": [
      "/v4/cores"
    ],
    "id": "VarChar(50),#key",
    "serial": "VarChar(50)",
    "block": "Integer",
    "status": "VarChar(50)",
    "reuse_count": "Integer",
    "rtls_attempts": "Integer",
    "rtls_landings": "Integer",
    "asds_attempts": "Integer",
    "asds_landings": "Integer",
    "last_update": "LongVarChar(1000)",
    "launches": "JSON"
  },
  "DRAGONS": {
    "#path": [
      "/v4/dragons"
    ],
    "id": "VarChar(50),#key",
    "name": "VarChar(100)",
    "type": "VarChar(50)",
    "active": "Boolean",
    "crew_capacity": "Integer",
    "sidewall_angle_deg": "Integer",
    "orbit_duration_yr": "Integer",
    "dry_mass_kg": "Integer",
    "dry_mass_lb": "Integer",
    "first_flight": "Date",
    "wikipedia": "VarChar(500)",
    "description": "LongVarChar(2000)",
    "heat_shield": "JSON",
    "launch_payload_mass": "JSON",
    "launch_payload_vol": "JSON",
    "return_payload_mass": "JSON",
    "return_payload_vol": "JSON",
    "pressurized_capsule": "JSON",
    "trunk": "JSON",
    "height_w_trunk": "JSON",
    "diameter": "JSON",
    "thrusters": "JSON",
    "flickr_images": "JSON"
  },
  "LAUNCHES": {
    "#path": [
      "/v4/launches"
    ],
    "id": "VarChar(50),#key",
    "flight_number": "Integer",
    "name": "VarChar(200)",
    "date_utc": "Timestamp",
    "date_unix": "BigInt",
    "date_local": "VarChar(50)",
    "date_precision": "VarChar(50)",
    "upcoming": "Boolean",
    "rocket": "VarChar(50)",
    "success": "Boolean",
    "details": "LongVarChar(5000)",
    "launchpad": "VarChar(50)",
    "auto_update": "Boolean",
    "tbd": "Boolean",
    "launch_library_id": "VarChar(100)",
    "static_fire_date_utc": "Timestamp",
    "static_fire_date_unix": "BigInt",
    "net": "Boolean",
    "window": "Integer",
    "fairings": "JSON",
    "links": "JSON",
    "failures": "JSON",
    "crew": "JSON",
    "ships": "JSON",
    "capsules": "JSON",
    "payloads": "JSON",
    "cores[]": {
      "core": "VarChar(50)",
      "flight": "Integer",
      "gridfins": "Boolean",
      "legs": "Boolean",
      "reused": "Boolean",
      "landing_attempt": "Boolean",
      "landing_success": "Boolean",
      "landing_type": "VarChar(50)",
      "landpad": "VarChar(50)"
    }
  },
  "LAUNCHPADS": {
    "#path": [
      "/v4/launchpads"
    ],
    "id": "VarChar(50),#key",
    "name": "VarChar(100)",
    "full_name": "VarChar(200)",
    "locality": "VarChar(100)",
    "region": "VarChar(100)",
    "latitude": "Double",
    "longitude": "Double",
    "launch_attempts": "Integer",
    "launch_successes": "Integer",
    "timezone": "VarChar(100)",
    "status": "VarChar(50)",
    "details": "LongVarChar(5000)",
    "rockets": "JSON",
    "launches": "JSON",
    "images": "JSON"
  },
  "LANDPADS": {
    "#path": [
      "/v4/landpads"
    ],
    "id": "VarChar(50),#key",
    "name": "VarChar(100)",
    "full_name": "VarChar(200)",
    "status": "VarChar(50)",
    "type": "VarChar(50)",
    "locality": "VarChar(100)",
    "region": "VarChar(100)",
    "latitude": "Double",
    "longitude": "Double",
    "landing_attempts": "Integer",
    "landing_successes": "Integer",
    "wikipedia": "VarChar(500)",
    "details": "LongVarChar(5000)",
    "launches": "JSON",
    "images": "JSON"
  },
  "PAYLOADS": {
    "#path": [
      "/v4/payloads"
    ],
    "id": "VarChar(50),#key",
    "name": "VarChar(200)",
    "type": "VarChar(100)",
    "reused": "Boolean",
    "launch": "VarChar(50)",
    "orbit": "VarChar(50)",
    "reference_system": "VarChar(50)",
    "regime": "VarChar(50)",
    "longitude": "Double",
    "semi_major_axis_km": "Double",
    "eccentricity": "Double",
    "periapsis_km": "Double",
    "apoapsis_km": "Double",
    "inclination_deg": "Double",
    "period_min": "Double",
    "lifespan_years": "Integer",
    "epoch": "Timestamp",
    "mean_motion": "Double",
    "raan": "Double",
    "arg_of_pericenter": "Double",
    "mean_anomaly": "Double",
    "mass_kg": "Double",
    "mass_lbs": "Double",
    "dragon": "JSON",
    "customers": "JSON",
    "norad_ids": "JSON",
    "nationalities": "JSON",
    "manufacturers": "JSON"
  },
  "SHIPS": {
    "#path": [
      "/v4/ships"
    ],
    "id": "VarChar(50),#key",
    "name": "VarChar(200)",
    "legacy_id": "VarChar(50)",
    "model": "VarChar(100)",
    "type": "VarChar(100)",
    "active": "Boolean",
    "imo": "Integer",
    "mmsi": "Integer",
    "abs": "Integer",
    "class": "Integer",
    "mass_kg": "Integer",
    "mass_lbs": "Integer",
    "year_built": "Integer",
    "home_port": "VarChar(200)",
    "status": "VarChar(100)",
    "speed_kn": "Double",
    "course_deg": "Double",
    "latitude": "Double",
    "longitude": "Double",
    "last_ais_update": "Timestamp",
    "link": "VarChar(500)",
    "image": "VarChar(500)",
    "roles": "JSON",
    "launches": "JSON"
  },
  "STARLINK": {
    "#path": [
      "/v4/starlink"
    ],
    "id": "VarChar(50),#key",
    "version": "VarChar(50)",
    "launch": "VarChar(50)",
    "longitude": "Double",
    "latitude": "Double",
    "height_km": "Double",
    "velocity_kms": "Double",
    "spaceTrack": "JSON"
  }
}