{
  "#hostname": "https://<host>:<port>",
  "TABLE_STANDARD": {
    "#path": [
      "/path/to/endpoint"
    ],
    "column1_1": "DataType,#key",
    "column2_1": "DataType"
  },
  "TABLE_WITHOUT_ID": {
    "#path": [
      "/path/to/endpoint2"
    ],
    "ROWID": "VarChar(32)=rowid(),#key",
    "column1_2": "DataType",
    "column2_2": "DataType",
    "column3_2": "DataType"
  },
  "TABLE_ALIAS": {
    "#path": [
      "/path/to/endpoint3"
    ],
    "column1_3<alias_name>": "DataType",
    "column2_3": "DataType"
  },
  "TABLE_NESTED_OBJECT": {
    "#path": [
      "/path/to/endpoint4"
    ],
    "column1_4": "DataType",
    "column2_4_nested_object": "JSON"
  },
  "TABLE_NESTED_ARRAY": {
    "#path": [
      "/path/to/endpoint5"
    ],
    "column1_5": "DataType",
    "column2_5_nested_array[]": {
      "nestedField1": "DataType",
      "nestedField2": "DataType"
    }
  },
  "TABLE_PARAM_1": {
    "#path": [
      "/path/to/endpoint6/{param1:sample_value_of_param1}"
    ],
    "param1": "DataType",
    "column1_6": "DataType",
    "column2_6": "DataType"
  },
  "TABLE_PARAM_2": {
    "#path": [
      "/path/to/endpoint7/{param1:sample_value_of_param1}"
    ],
    "param1": {
       "#type":"DataType",
       "#eq":"param1",
       "#virtual":true
    },
    "column1_7": "DataType"
  },
  "TABLE_PATHS": {
    "#path": [
      "/path/to/endpoint8/first_endpoint",
      "/path/to/endpoint8/second_endpoint",
      "/path/to/endpoint8/third_endpoint"
    ],
    "column1_8": "DataType",
    "column2_8": "DataType"
  },
  "TABLE_COMBINED_EXAMPLE": {
    "#path": [
      "/path/to/endpoint9/first_endpoint",
      "/path/to/endpoint9/second_endpoint/{param1:sample_value_of_param1}",
      "/path/to/endpoint9/{param2:sample_value_of_param2}/third_endpoint"
    ],
    "ROWID": "VarChar(32)=rowid(),#key",
    "param1": {
       "#type":"DataType",
       "#eq":"param1",
       "#virtual":true
    },
    "column1_9": "DataType",
    "column2_9<alias_name>": "DataType",
    "column3_9": "DataType",
    "column4_9_nested_array[]": {
      "nestedField1": "DataType",
      "nestedField2": "DataType"
    }
  }  
}
