#********************************************************
#                                                       *
#  (C) Copyright IBM Corp. 2025                         *
#                                                       *
#********************************************************

METHOD_NOT_IMPLEMENTED = {0} not implemented
