#********************************************************
#                                                       *
#  (C) Copyright IBM Corp. 2025                         *
#                                                       *
#********************************************************

CANNOT_CONSTRUCT_ARROW_DECIMAL_TYPE = Cannot construct ArrowLargeDecimalType from underlying type {0}
CANNOT_SET_BYTES = Cannot set bytes for this arrow type
INVALID_CRITERIA = Invalid criteria
MISSING_ACTION_BODY = Missing action body
MISSING_ASSET = Missing asset
MISSING_ASSET_ID = Missing asset id
MISSING_PARTITION_INDEX = Missing partition index
NO_FLIGHT_DESCRIPTOR_FOR_TICKET = No flight descriptor available for the given ticket
UNEXPECTED_DATE_OBJECT_TYPE = Unexpected date object type ({0})
UNEXPECTED_TIME_OBJECT_TYPE = Unexpected time object type ({0})
UNEXPECTED_TIMESTAMP_OBJECT_TYPE = Unexpected timestamp object type ({0})
UNRECOGNIZED_DURATION_VALUE = Unrecognized duration value: {0}
UNSUPPORTED_ARROW_EXTENSION_TYPE = Unsupported arrow extension type: {0}
UNSUPPORTED_ARROW_TYPE = Unsupported arrow type: {0}
