#********************************************************
#                                                       *
#  (C) Copyright IBM Corp. 2025                         *
#                                                       *
#********************************************************

DATASOURCE_TYPE_NOT_SUPPORTED = Data source type {0} is not supported
INVALID_DRIVER = Driver [{0}] is not one of {1}
INVALID_JDBC_URL = Invalid JDBC URL {0}
INVALID_PROPERTY = Invalid {0}
MISSING_PROPERTY = Missing {0}
