#********************************************************
#                                                       *
#  (C) Copyright IBM Corp. 2026                         *
#                                                       *
#********************************************************

OBJECT_DOES_NOT_EXIST = The S3 object at key {0} does not exist
OBJECT_IS_A_PREFIX = The key {0} refers to a prefix (folder), not a file object
ACL_DISABLED = S3 Object ACLs are disabled for bucket {0} (BucketOwnerEnforced ownership). Returning empty ACL.
