#********************************************************
#                                                       *
#  (C) Copyright IBM Corp. 2026                         *
#                                                       *
#********************************************************

OBJECT_DOES_NOT_EXIST = The S3 object at key {0} does not exist
ACL_DISABLED = S3 Object ACLs are disabled for bucket {0} (BucketOwnerEnforced ownership). Returning empty ACL.
