#********************************************************
#                                                       *
#  (C) Copyright IBM Corp. 2025                         *
#                                                       *
#********************************************************

REQUIRED_PROPERTY_VALUE = The property {0} is required to have a value of {1} but has a value of {2}
TARGET_INTERACTION_NOT_SUPPORTED = Data source type {0} is not supported as a target
