#********************************************************
#                                                       *
#  (C) Copyright IBM Corp. 2025                         *
#                                                       *
#********************************************************

INVALID_PATH = Invalid path
MISSING_ONE_OF_PROPERTIES = Missing one of {0}
MISSING_LENGTH_FOR_FIELD = Missing length for field {0}
MISSING_PROPERTY = Missing {0}
UNKNOWN_TYPE = Unknown type {0}
UNSUPPORTED_ACTION = doAction {0} is not supported
UNSUPPORTED_DATA_TYPE_FOR_COLUMN = Unsupported data type for column {0}
