#********************************************************
#                                                       *
#  (C) Copyright IBM Corp. 2025                         *
#                                                       *
#********************************************************

INVALID_CRITERIA = Invalid criteria
MISSING_ACTION_BODY = Missing action body
MISSING_DATASOURCE_TYPE_NAME = Missing data source type name
